version: "3"

services: 
  frontend:
    build: frontend/
    command: yarn start
    ports:
      - '7000:7000'
    volumes:
      - ./frontend:/usr/app
    depends_on: 
      - backend
  
  backend:
    build: backend/
    command: yarn start
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/app
    depends_on: 
      - db

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432      